name: countdown
description: Countdown is countdown with pause/resume controls
version: 0.1.0
author: Benjamin NGUYEN <benjamin.kim.nguyen@gmail.com>
homepage: https://github.com/BenNG/countdown
dev_dependencies:
  test: ^1.5.1
  quiver: any
